version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dungnv
      - MONGO_INITDB_ROOT_PASSWORD=10031992
      - MONGO_INITDB_DATABASE=test


