name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: dungnv45
        password: b76fe7cf-30f6-42aa-87be-a9d3ec072a0c

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dungnv45/simple-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        id: install


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name my-eks-cluster --region ap-southeast-1


      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f kube/k8s-deployment.yaml
          kubectl apply -f kube/mongo.yaml
          kubectl apply -f kube/balance-service.yaml

      - name: restart kubernetes for apply latest image
        run: |
          kubectl rollout restart deployments -n kube-system
          kubectl rollout restart deployment
